version: '3'
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - database
    depends_on:
      - backend
    # volumes:
    #   - frontend:/frontend

  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "8091:8091"
      - "8090:8090"
    networks:
      - database
    depends_on:
      - mysql
    environment:
      - DB_HOST=db
      - DB_PASSWORD=my
      - DB_USER=root
      - DB_NAME=book_admin
      - DB_PORT=5432
    # volumes:
    #   - backend:/backend

  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    networks:
      - database
    ports:
      - "5432:5432"
    environment:
      MYSQL_DATABASE: book_admin
      MYSQL_ROOT_PASSWORD: my
    volumes:
    #   - ./backend/data:/var/lib/mysql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    user: mysql

# volumes:
  # data:
  # frontend:
  # backend:

networks:
  database:
    driver: bridge
    external: true
  backend:
    driver: bridge
    external: true
  frontend:
    driver: bridge
    external: true
  