version: '3'
services:

  app:
    container_name: app
    build: .
    ports:
      - "8090:8090"
    networks:
      - database
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=db
      - DB_PASSWORD=post
      - DB_USER=post
      - DB_NAME=postgres
      - DB_PORT=5432
    volumes:
      - .:/go/src/WEB

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:9.5
    container_name: db
    restart: always
    networks:
      - database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post

    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:

networks:
  database:
    driver: bridge
    external: true