/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    IEpWarningFilled: typeof import('~icons/ep/warning-filled')['default']
    IEpWarnTriangleFilled: typeof import('~icons/ep/warn-triangle-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
